---
#Installs docker engine on all hosts
- hosts: all
  remote_user: ubuntu
  tasks:
    - name: add docker public key
      command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
      become: true

    - name: touch docker.list
      command: touch /etc/apt/sources.list.d/docker.list
      become: true

    - name: add docker repo
      shell: echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | tee /etc/apt/sources.list.d/docker.list
      become: true

    - name: update package list
      apt: update_cache=yes
      become: true

    - name: install docker engine
      shell: apt-get install linux-image-extra-$(uname -r) 
      become: true

    - name: install docker engine
      apt: name=docker-engine 
      become: true

    - name: start docker
      service: name=docker state=started
      become: true

    - name: add user group
      command: usermod -a -G docker ubuntu
      become: true
